@baseUrl = {{url}}/api/v1/carts

@productId = {{$random.number.digit}}
@quantity = {{$random.number.digit}}

### Получить корзину (метаданные, сумма, количество)
GET {{baseUrl}} HTTP/1.1

### Очистить корзину
DELETE {{baseUrl}} HTTP/1.1

### Добавить товар в корзину
POST {{baseUrl}}/items HTTP/1.1
Content-Type: application/json

{
  "productId": {{productId}},
  "quantity": {{quantity}}
}

### Получить все товары в корзине
GET {{baseUrl}}/items HTTP/1.1

### Получение продукта из корзины по ID продукта
GET {{baseUrl}}/items/{{productId}} HTTP/1.1

### Изменить количество товара
PATCH {{baseUrl}}/items/{{productId}} HTTP/1.1
Content-Type: application/json

{
  "quantity": 12
}

### Удалить товар из корзины
DELETE {{baseUrl}}/items/{{productId}} HTTP/1.1