INSERT INTO categories (name, created_at)
VALUES  ('Electronics', NOW()),
        ('Clothing', NOW()),
        ('Shoes', NOW()),
        ('Accessories', NOW()),
        ('Bags', NOW()),
        ('Watches', NOW()),
        ('Beauty & Personal Care', NOW()),
        ('Health & Wellness', NOW()),
        ('Home & Kitchen', NOW()),
        ('Furniture', NOW()),
        ('Sports & Outdoors', NOW()),
        ('Toys & Games', NOW()),
        ('Books', NOW()),
        ('Music', NOW()),
        ('Movies & Entertainment', NOW()),
        ('Food & Beverages', NOW()),
        ('Pet Supplies', NOW()),
        ('Automotive', NOW()),
        ('Tools & Hardware', NOW()),
        ('Office Supplies', NOW()),
        ('Jewelry', NOW()),
        ('Baby Products', NOW()),
        ('Garden & Outdoor', NOW()),
        ('Travel & Luggage', NOW()),
        ('Software', NOW()),
        ('Smart Home', NOW()),
        ('Groceries', NOW()),
        ('Stationery', NOW()),
        ('Art & Crafts', NOW());