CREATE TABLE order_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    order_id    BIGINT                                  NOT NULL,
    product_id  BIGINT                                  NOT NULL,
    price       DECIMAL                                 NOT NULL,
    quantity    BIGINT                                  NOT NULL,
    total_price DECIMAL                                 NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);