INSERT INTO brands (name, image_url, created_at)
VALUES  ('Apple', 'https://example.com/images/apple.png', NOW()),
        ('Samsung', 'https://example.com/images/samsung.png', NOW()),
        ('Nike', 'https://example.com/images/nike.png', NOW()),
        ('Adidas', 'https://example.com/images/adidas.png', NOW()),
        ('Sony', 'https://example.com/images/sony.png', NOW()),
        ('Microsoft', 'https://example.com/images/microsoft.png', NOW()),
        ('Google', 'https://example.com/images/google.png', NOW()),
        ('Amazon', 'https://example.com/images/amazon.png', NOW()),
        ('Tesla', 'https://example.com/images/tesla.png', NOW()),
        ('BMW', 'https://example.com/images/bmw.png', NOW()),
        ('Mercedes-Benz', 'https://example.com/images/mercedes.png', NOW()),
        ('Toyota', 'https://example.com/images/toyota.png', NOW()),
        ('Coca-Cola', 'https://example.com/images/cocacola.png', NOW()),
        ('Pepsi', 'https://example.com/images/pepsi.png', NOW()),
        ('Starbucks', 'https://example.com/images/starbucks.png', NOW()),
        ('McDonald', 'https://example.com/images/mcdonalds.png', NOW()),
        ('KFC', 'https://example.com/images/kfc.png', NOW()),
        ('Louis Vuitton', 'https://example.com/images/louisvuitton.png', NOW()),
        ('Gucci', 'https://example.com/images/gucci.png', NOW()),
        ('Zara', 'https://example.com/images/zara.png', NOW()),
        ('H&M', 'https://example.com/images/hm.png', NOW()),
        ('IKEA', 'https://example.com/images/ikea.png', NOW()),
        ('Lego', 'https://example.com/images/lego.png', NOW()),
        ('Intel', 'https://example.com/images/intel.png', NOW()),
        ('AMD', 'https://example.com/images/amd.png', NOW()),
        ('Huawei', 'https://example.com/images/huawei.png', NOW()),
        ('Xiaomi', 'https://example.com/images/xiaomi.png', NOW()),
        ('Rolex', 'https://example.com/images/rolex.png', NOW()),
        ('Puma', 'https://example.com/images/puma.png', NOW()),
        ('Under Armour', 'https://example.com/images/underarmour.png', NOW());