CREATE TABLE user_addresses
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT                                  NOT NULL,
    delivery_address VARCHAR(255)                            NOT NULL,
    is_primary       BOOLEAN,
    CONSTRAINT pk_user_addresses PRIMARY KEY (id)
);

ALTER TABLE user_addresses
    ADD CONSTRAINT FK_USER_ADDRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);