INSERT INTO products (name, description, price, quantity, image_url, category_id, brand_id, created_at)
VALUES  ('Пылесос', 'Современный пылесос от компании HIGH TECH', 49.99, 12, 'https://example.com/products/vacuum.jpg', 9, 2, NOW()),
        ('Холодильник', 'Энергоэффективный холодильник с системой No Frost', 399.99, 5, 'https://example.com/products/fridge.jpg', 9, 3, NOW()),
        ('Телевизор', 'LED-телевизор с диагональю 55 дюймов и поддержкой 4K', 699.99, 8, 'https://example.com/products/tv.jpg', 1, 5, NOW()),
        ('Ноутбук', 'Мощный ноутбук для работы и игр', 999.99, 15, 'https://example.com/products/laptop.jpg', 1, 6, NOW()),
        ('Смартфон', 'Смартфон с камерой 108 Мп и OLED дисплеем', 799.99, 20, 'https://example.com/products/smartphone.jpg', 1, 7, NOW()),
        ('Наушники', 'Беспроводные наушники с шумоподавлением', 149.99, 25, 'https://example.com/products/headphones.jpg', 1, 8, NOW()),
        ('Планшет', 'Планшет с диагональю 11 дюймов и поддержкой стилуса', 499.99, 10, 'https://example.com/products/tablet.jpg', 1, NULL, NOW()),
        ('Умные часы', 'Смарт-часы с датчиком пульса и GPS', 199.99, 30, 'https://example.com/products/smartwatch.jpg', 1, 7, NOW()),
        ('Кофеварка', 'Автоматическая кофеварка с функцией капучино', 249.99, 6, 'https://example.com/products/coffeemaker.jpg', 9, 12, NOW()),
        ('Микроволновка', 'Микроволновая печь с грилем и конвекцией', 179.99, 12, 'https://example.com/products/microwave.jpg', 9, 13, NOW()),
        ('Электросамокат', 'Складной электросамокат с запасом хода 25 км', 599.99, 7, 'https://example.com/products/scooter.jpg', 11, NULL, NOW()),
        ('Фен', 'Компактный фен с функцией ионизации', 39.99, 18, 'https://example.com/products/hairdryer.jpg', 7, 15, NOW()),
        ('Фотоаппарат', 'Зеркальная камера с объективом 18-55 мм', 899.99, 4, 'https://example.com/products/camera.jpg', 1, 5, NOW()),
        ('Монитор', 'Игровой монитор 27 дюймов, 165 Гц', 329.99, 9, 'https://example.com/products/monitor.jpg', 1, 6, NOW()),
        ('Принтер', 'МФУ с функцией Wi-Fi и двусторонней печатью', 129.99, 11, 'https://example.com/products/printer.jpg', 1, NULL, NOW()),
        ('Стиральная машина', 'Фронтальная загрузка, экономичный режим', 549.99, 3, 'https://example.com/products/washingmachine.jpg', 9, 3, NOW()),
        ('Миксер', 'Ручной миксер с 5 скоростями', 29.99, 14, 'https://example.com/products/mixer.jpg', 9, NULL, NOW()),
        ('Тостер', 'Тостер на 2 ломтика с функцией разморозки', 24.99, 19, 'https://example.com/products/toaster.jpg', 9, NULL, NOW()),
        ('Пылесос-робот', 'Робот-пылесос с навигацией и док-станцией', 399.99, 8, 'https://example.com/products/robotvacuum.jpg', 9, 2, NOW()),
        ('Колонка', 'Bluetooth колонка с защитой от влаги', 59.99, 22, 'https://example.com/products/speaker.jpg', 1, 7, NOW()),
        ('Гриль', 'Электрический гриль для дома', 89.99, 10, 'https://example.com/products/grill.jpg', 9, 12, NOW()),
        ('Утюг', 'Паровой утюг с керамической подошвой', 49.99, 16, 'https://example.com/products/iron.jpg', 9, NULL, NOW()),
        ('Кондиционер', 'Настенный кондиционер с режимом обогрева', 799.99, 5, 'https://example.com/products/ac.jpg', 9, 3, NOW()),
        ('Вентилятор', 'Напольный вентилятор с пультом ДУ', 69.99, 17, 'https://example.com/products/fan.jpg', 9, NULL, NOW()),
        ('Блендер', 'Стационарный блендер для смузи и коктейлей', 79.99, 9, 'https://example.com/products/blender.jpg', 9, NULL, NOW()),
        ('Электрочайник', 'Чайник из нержавеющей стали, 1.7 л', 39.99, 20, 'https://example.com/products/kettle.jpg', 9, 12, NOW()),
        ('Видеокарта', 'Игровая видеокарта с 12 Гб памяти', 1199.99, 6, 'https://example.com/products/gpu.jpg', 1, 6, NOW()),
        ('Клавиатура', 'Механическая клавиатура с RGB подсветкой', 99.99, 13, 'https://example.com/products/keyboard.jpg', 1, 7, NOW()),
        ('Мышь', 'Игровая мышь с 7 программируемыми кнопками', 49.99, 18, 'https://example.com/products/mouse.jpg', 1, 7, NOW()),
        ('Веб-камера', 'Full HD веб-камера с автофокусом', 79.99, 12, 'https://example.com/products/webcam.jpg', 1, NULL, NOW()),
        ('Смарт-лампа', 'Wi-Fi лампа с регулировкой яркости и цвета', 29.99, 25, 'https://example.com/products/smartlamp.jpg', 27, NULL, NOW()),
        ('Проектор', 'Full HD проектор для домашнего кинотеатра', 459.99, 4, 'https://example.com/products/projector.jpg', 1, 5, NOW()),
        ('Саундбар', 'Акустическая система 2.1 для телевизора', 299.99, 8, 'https://example.com/products/soundbar.jpg', 1, 5, NOW()),
        ('Роутер', 'Wi-Fi 6 маршрутизатор с MU-MIMO', 159.99, 10, 'https://example.com/products/router.jpg', 1, 6, NOW()),
        ('Соковыжималка', 'Центробежная соковыжималка для овощей и фруктов', 129.99, 7, 'https://example.com/products/juicer.jpg', 9, NULL, NOW()),
        ('Швейная машина', 'Электронная швейная машина с 60 программами', 349.99, 5, 'https://example.com/products/sewingmachine.jpg', 9, NULL, NOW()),
        ('Электроплита', 'Индукционная плита с сенсорным управлением', 499.99, 3, 'https://example.com/products/stove.jpg', 9, NULL, NOW()),
        ('Духовка', 'Встраиваемая электрическая духовка', 599.99, 4, 'https://example.com/products/oven.jpg', 9, NULL, NOW()),
        ('Посудомойка', 'Компактная посудомоечная машина на 6 комплектов', 379.99, 6, 'https://example.com/products/dishwasher.jpg', 9, 3, NOW()),
        ('Триммер', 'Универсальный триммер для волос и бороды', 59.99, 15, 'https://example.com/products/trimmer.jpg', 7, NULL, NOW()),
        ('Электробритва', 'Роторная электробритва с плавающими головками', 89.99, 11, 'https://example.com/products/shaver.jpg', 7, NULL, NOW()),
        ('Геймпад', 'Беспроводной геймпад для ПК и консолей', 69.99, 20, 'https://example.com/products/gamepad.jpg', 1, 6, NOW()),
        ('Флешка', 'USB флеш-накопитель 128 Гб', 24.99, 30, 'https://example.com/products/flashdrive.jpg', 1, 6, NOW()),
        ('SSD диск', 'Твердотельный накопитель 1 Тб', 139.99, 12, 'https://example.com/products/ssd.jpg', 1, 6, NOW()),
        ('Жесткий диск', 'HDD на 2 Тб для ПК и серверов', 89.99, 10, 'https://example.com/products/hdd.jpg', 1, 6, NOW()),
        ('Оперативная память', 'DDR4 модуль 16 Гб 3200 МГц', 69.99, 14, 'https://example.com/products/ram.jpg', 1, 6, NOW()),
        ('Материнская плата', 'Совместимая с последними процессорами Intel', 229.99, 5, 'https://example.com/products/motherboard.jpg', 1, 6, NOW()),
        ('Процессор', '8-ядерный процессор для настольного ПК', 399.99, 6, 'https://example.com/products/cpu.jpg', 1, 6, NOW()),
        ('Зарядное устройство', 'Универсальное зарядное с поддержкой PD 65W', 39.99, 21, 'https://example.com/products/charger.jpg', 1, 7, NOW()),
        ('Powerbank', 'Внешний аккумулятор 20000 мАч с QC 3.0', 59.99, 18, 'https://example.com/products/powerbank.jpg', 1, 7, NOW());
