@baseUrl = {{url}}/api/v1/users

@firstName = {{$random.name.firstName}}
@lastName = {{$random.name.lastName}}
@address = {{$random.address.fullAddress}}

### Обновление всех полей кроме email и пароля
PATCH {{baseUrl}}/ HTTP/1.1
Content-Type: multipart/form-data; boundary="delimiter12345"

--delimiter12345
Content-Disposition: form-data; name="firstName"

{{firstName}}

--delimiter12345
Content-Disposition: form-data; name="lastName"

{{lastName}}

--delimiter12345
Content-Disposition: form-data; name="deliveryAddress"

{{address}}

--delimiter12345
Content-Disposition: form-data; name="avatar"; filename="avatar.png"

< ./files/user-avatar.png

--delimiter12345--